language: node_js

node_js:
  - "node"
cache:
  npm: false

before_install:
  - rvm install 2.6.2
  - gem install awesome_bot
  - cd tests && npm install chalk && cd ..

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make checks_pr; fi
  - 'if [ "$TRAVIS_BRANCH" == "monthly-check" ]; then make monthly; fi'

notifications:
  email: false
